### ISSUE TITLE
Configure the 404 error page

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/decidim-vilanova-static-website#28]
In Netlify, the 404 error page is not configured.

**Comment by xredo** [comment]
The 404 page is not configurable in Netlify. It just looks for a static file in the root directory named: 404.html.

You'll need to create a non translatable version of the 404 page (better in Catalan, as it's the default language) with no middleman code and the styles inline. And place it in the **root/404.html**.

Also, I recommend you to remove the i18n select because it won't work properly.
